name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user_name: analuisa433
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
